<?php

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

function hello_block_info() {
  $blocks = array();
  
  $blocks['hello world'] = array(
    'info' => t('Hello World'),
           
  );
  $blocks['hello user'] = array(
    'info' => t('Hello User Block'),
  );
  $blocks['user_info'] = array(
    'info' => t('User info Block'),
  );
  
  return $blocks;
}

function hello_block_view($delta = '') {
  $block = array();
  
  switch($delta) {
    case 'hello world';
      $block['subject'] = t('Hello World!!!');
      $block['content'] = t('This is the hello world block ');
      break;
    case 'hello user';
      $block['subject'] = t('Hello world');
      
      $hour = date('G');
      $greeting = '';
      if ($hour < 12) {
        $greeting = 'Good morning @name!';
      }
      elseif ($hour < 18) {
        $greeting = 'Good afternoon @name!' ;
      }
      else {
        $greeting = 'Good evening @name!' ;
      }
      
      global $user;
      $block['content'] = t($greeting . ' hour=' . $hour, array('@name' => $user->name));
      break; 
      
    case 'user_info':
        
      if (arg(0) == 'user' && is_numeric(arg(1))) {
        $account = user_load(arg(1));
        if (module_exists('devel')) {
          dpm($account);
        }
        if (!empty($account)); {
          $block['subject'] = t('User info');
          $output = '';
          $output .= '<div><label>' . t('Name') . '</label>' . $account->name . '</div>';
          $output .= '<div><label>' . t('Email') . '</label>' . $account->mail . '</div>';
          $output .= '<div><label>' . t('Created') . '</label>' . format_date($account->created) . '</div>';
          $access = ($account->access == 0) ? t('Never') : format_date($account->access);
          $output .= '<div><label>' . t('Last Access') . '</label>' . $access . '</div>';
          $block['content'] = $output;
        }
                
      }
      break;
  }
  
  return $block;
}